### ISSUE TITLE
Unable to find Ark's KPart component

### ISSUE THREAD

**Issue by probonopd** [appimage-packages/ark#3]
On `ubuntu-16.04-desktop-amd64.iso`, `ark-1.0-x86_64.AppImage` gives `"Unable to find Ark's KPart component, please check your installation."`

**Comment by ScarlettGatelyMoore** [comment]
It has something to do with kbuildsycoca5. I am looking into it.

**Comment by ScarlettGatelyMoore** [comment]
It is missing kparts plugins. Which should be fixed when I get a good build ( having some other issues )

**Comment by ScarlettGatelyMoore** [comment]
Still not fixed. Definitely a plugin issue though.

**Comment by ScarlettGatelyMoore** [comment]
Fixed

**Comment by probonopd** [comment]
ark-git20170115-x86_64.AppImage says:
> ark.main: Error loading Ark KPart.

**Comment by ScarlettGatelyMoore** [comment]
trying to fix theme issue, it will be broken for a bit
